name = "GoldfarbIdnaniSolver"
uuid = "906ccaf3-f60c-4d27-be89-7848ae703cf8"
authors = ["Fabien Le Floc'h <fabien_lefloch@2ipi.com>"]
version = "1.1.3"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
#COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
#Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
StatsBase = "0.33, 0.34"
BenchmarkTools = "1"
julia = "1"
